name: Build & Publish Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - '*' # 或更精确的 'v*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Releasing using Hub
      uses: sangatdesai/release-apk@v4
    - name: Create local.properties
      run: echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        APP_FOLDER: app
